name: Android CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run lint checks
      run: ./gradlew lint
    - name: Build apk debug project (APK)
      run: ./gradlew assembleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk